### ISSUE TITLE
`build_header` function missing in `bin/list-all`

### ISSUE THREAD

**Issue by joschi** [particledecay/asdf-yadm#1]
The `bin/list-all` script is missing the `build_header` function, leading to the following error when running `asdf list-all yadm`:
```
Plugin yadm's list-all callback script failed with output:
/home/runner/.asdf/plugins/yadm/bin/list-all: line 14: build_header: command not found
```

The `build_header` function exists in the `bin/download` script:
https://github.com/particledecay/asdf-yadm/blob/f268195f81bd1793b09eeddadf8a9d45cde4e27e/bin/download#L45-L50

Refs https://github.com/asdf-vm/asdf/pull/881

**Comment by particledecay** [comment]
Fixed in https://github.com/particledecay/asdf-yadm/pull/2. Thanks for the issue report!

**Comment by joschi** [comment]
@particledecay Unfortunately it still doesn't work because the `build_header` function is defined after its first usage if `$OAUTH_TOKEN` is set.

```
# OAUTH_TOKEN=1 bin/list-all
bin/list-all: line 14: build_header: command not found
```
